name: Bug Report
description: Create a report to help us improve Musly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the problem...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of the app are you using? (e.g., v1.0.0-beta)
    validations:
      required: true
  - type: input
    id: server
    attributes:
      label: Subsonic Server
      description: What server software are you using? (e.g., Navidrome, Gonic)
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please provide any relevant logs or error messages.
      render: shell
